{"context": "\n\u52d5\u4f5c\u74b0\u5883\nSketchUp Make v17.1.173\nMacOS X El Capitan\n\n\n\u95a2\u9023\u3000http://qiita.com/7of9/items/ff5921cf65b5f88d9311\n\u9078\u629e\u3057\u305fGroup\u3092\u5ea7\u6a19(0,0,0)\u306b\u79fb\u52d5\u3057\u3066\u307f\u308b\u3002\n\u53c2\u8003(Group) http://ruby.sketchup.com/Sketchup/Group.html\norigin\u3068\u3044\u3046\u30d7\u30ed\u30d1\u30c6\u30a3\u3092\u53c2\u8003\u306b\u3057\u305f\u3002\n\u53c2\u8003(Point3d) http://ruby.sketchup.com/Geom/Point3d.html\norigin\u306fPoint3d\u578b\u306e\u3088\u3046\u3060\u3002\n\ncode\nGroup\u306e\u4f4d\u7f6e(origin)\u3092\u53d6\u5f97\u3057\u3066\u3001\u305d\u306e\u53cd\u5bfe\u306e\u5927\u304d\u3055\u306e\u79fb\u52d5\u3092\u3059\u308b\u3068\u3044\u3046\u65b9\u91dd\u3002\n\nalign161230.rb\nrequire 'sketchup.rb'\n\ndef align_group_to_worldOrigin()\n    model = Sketchup.active_model\n    my_selection = model.selection\n\n    my_selection.each do |ent|\n        if ent.is_a? Sketchup::Group\n            tr = ent.transformation\n            org = tr.origin # :Point3d\n            pnt = Geom::Point3d.new(-org[0], -org[1], -org[2])\n            mve = Geom::Transformation.new(pnt)\n            ent.transform! mve\n        end\n    end\nend\n\n\n\u79fb\u52d5\u524d\n\n\u79fb\u52d5\u5f8c\n\n```txt:\u52d5\u4f5c\u74b0\u5883\nSketchUp Make v17.1.173\nMacOS X El Capitan\n```\n\n\u95a2\u9023\u3000http://qiita.com/7of9/items/ff5921cf65b5f88d9311\n\n\u9078\u629e\u3057\u305fGroup\u3092\u5ea7\u6a19(0,0,0)\u306b\u79fb\u52d5\u3057\u3066\u307f\u308b\u3002\n\n\u53c2\u8003(Group) http://ruby.sketchup.com/Sketchup/Group.html\norigin\u3068\u3044\u3046\u30d7\u30ed\u30d1\u30c6\u30a3\u3092\u53c2\u8003\u306b\u3057\u305f\u3002\n\n\u53c2\u8003(Point3d) http://ruby.sketchup.com/Geom/Point3d.html\norigin\u306fPoint3d\u578b\u306e\u3088\u3046\u3060\u3002\n\n### code\n\nGroup\u306e\u4f4d\u7f6e(origin)\u3092\u53d6\u5f97\u3057\u3066\u3001\u305d\u306e\u53cd\u5bfe\u306e\u5927\u304d\u3055\u306e\u79fb\u52d5\u3092\u3059\u308b\u3068\u3044\u3046\u65b9\u91dd\u3002\n\n```align161230.rb\nrequire 'sketchup.rb'\n\ndef align_group_to_worldOrigin()\n    model = Sketchup.active_model\n    my_selection = model.selection\n\n    my_selection.each do |ent|\n        if ent.is_a? Sketchup::Group\n            tr = ent.transformation\n            org = tr.origin # :Point3d\n            pnt = Geom::Point3d.new(-org[0], -org[1], -org[2])\n    \t    mve = Geom::Transformation.new(pnt)\n            ent.transform! mve\n        end\n    end\nend\n```\n\n\u79fb\u52d5\u524d\n\n![qiita.png](https://qiita-image-store.s3.amazonaws.com/0/32870/148c2c25-c235-f69a-bfb8-9d2609961b07.png)\n\n\u79fb\u52d5\u5f8c\n\n![qiita.png](https://qiita-image-store.s3.amazonaws.com/0/32870/12f1f060-dd3f-bcf1-dc99-99ef7ed16c35.png)\n\n\n", "tags": ["SketchUp", "Ruby", "geometry"]}