{"context": "\n\n\u6982\u8981\nSketchUp\u3067ROK\u30d5\u30a1\u30a4\u30eb\u3092\u8aad\u307f\u8fbc\u3093\u3067\u898b\u305f\u3002\n\n\u5199\u771f\n\n\n\u74b0\u5883\nSketchUp\nv7.1.6860\nv8.0.16846\n\n\u30b5\u30f3\u30d7\u30eb\u30b3\u30fc\u30c9\nrok_ld.rb\nrequire 'sketchup.rb'\n\ndef rok_ld\n  entities = Sketchup.active_model.entities\n  vnam = 0\n  lnam = 0\n  state = 0\n  fmod = 0\n  verts = 0\n  x, y, z, s, e = 0\n  c = 0\n  v = []\n  l = []\n  f = UI.openpanel \"Select .rok file\", \"\", \"*.rok\"\n  return unless f\n  lines = IO.readlines(f, \"\\r\")\n  lines.each do | line |\n    line.strip!\n    case line\n    when \"POINT\"\n      state = 1\n    when \"LINE0\"\n      state = 2\n      lnam = 0\n    when \"FACE0\"\n      state = 3\n    when \"END00\"\n      UI.messagebox \"ok\"\n    else\n      if state > 0\n         c += 1\n      end\n      if state == 1\n        if c == 1\n          vnam = Integer(line)\n        end\n        if c == 6\n          x = Float(line)\n        end\n        if c == 7\n          y = Float(line)\n        end\n        if c == 8\n          z = Float(line)\n        end\n        if c == 8\n          v[vnam] = [x * 10, z * 10, -y * 10]\n          c = 0\n        end\n      end\n      if state == 2\n        if c == 1\n          s = Integer(line)\n        end\n        if c == 2\n          e = Integer(line)\n        end\n        if c == 3\n          lnam += 1\n        end\n        if c == 4\n          l[lnam] = [s, e]\n          c = 0\n        end\n      end\n      if state == 3\n        if c == 1\n          fmod = Integer(line)\n        end\n        if c == 2\n          f = []\n        end\n        if c == 4\n          f[0] = Integer(line)\n        end\n        if c == 5\n          f[1] = Integer(line)\n        end\n        if c == 6\n          f[2] = Integer(line)\n          if fmod == 3\n            verts = [v[l[f[0]][0]], v[l[f[0]][1]], v[l[f[1]][0]], v[l[f[1]][1]], v[l[f[2]][0]], v[l[f[2]][1]]]\n            verts.uniq!\n            begin\n              entities.add_face verts\n            rescue\n              UI.messagebox fmod\n            end\n            c = 0\n          end\n        end\n        if c == 7\n          f[3] = Integer(line)\n          if fmod == 4\n            verts = [v[l[f[0]][0]], v[l[f[0]][1]], v[l[f[1]][0]], v[l[f[1]][1]], v[l[f[2]][0]], v[l[f[2]][1]] , v[l[f[3]][0]], v[l[f[3]][1]]]\n            verts.uniq!\n            begin\n              entities.add_face verts\n            rescue\n              entities.add_face [verts[0], verts[1], verts[2]]\n              entities.add_face [verts[2], verts[3], verts[0]]\n            end\n            c = 0\n          end\n        end\n      end\n    end\n  end\nend\n\nif (not file_loaded?(\"rok_ld.rb\"))\n  UI.menu(\"Plugin\").add_item(\"rok_loader\") {rok_ld}\nend\n\nfile_loaded(\"rok_ld.rb\")\n\n\n#\u6982\u8981\nSketchUp\u3067ROK\u30d5\u30a1\u30a4\u30eb\u3092\u8aad\u307f\u8fbc\u3093\u3067\u898b\u305f\u3002\n\n#\u5199\u771f\n![rok.jpg](https://qiita-image-store.s3.amazonaws.com/0/18104/b7a421bf-3b6a-38ff-a18f-ffcc98d705f9.jpeg)\n\n\n#\u74b0\u5883\nSketchUp\nv7.1.6860\nv8.0.16846\n\n#\u30b5\u30f3\u30d7\u30eb\u30b3\u30fc\u30c9\nrok_ld.rb\n\n```\nrequire 'sketchup.rb'\n\ndef rok_ld\n  entities = Sketchup.active_model.entities\n  vnam = 0\n  lnam = 0\n  state = 0\n  fmod = 0\n  verts = 0\n  x, y, z, s, e = 0\n  c = 0\n  v = []\n  l = []\n  f = UI.openpanel \"Select .rok file\", \"\", \"*.rok\"\n  return unless f\n  lines = IO.readlines(f, \"\\r\")\n  lines.each do | line |\n    line.strip!\n    case line\n    when \"POINT\"\n      state = 1\n    when \"LINE0\"\n      state = 2\n      lnam = 0\n    when \"FACE0\"\n      state = 3\n    when \"END00\"\n      UI.messagebox \"ok\"\n    else\n      if state > 0\n         c += 1\n      end\n      if state == 1\n        if c == 1\n          vnam = Integer(line)\n        end\n        if c == 6\n          x = Float(line)\n        end\n        if c == 7\n          y = Float(line)\n        end\n        if c == 8\n          z = Float(line)\n        end\n        if c == 8\n          v[vnam] = [x * 10, z * 10, -y * 10]\n          c = 0\n        end\n      end\n      if state == 2\n        if c == 1\n          s = Integer(line)\n        end\n        if c == 2\n          e = Integer(line)\n        end\n        if c == 3\n          lnam += 1\n        end\n        if c == 4\n          l[lnam] = [s, e]\n          c = 0\n        end\n      end\n      if state == 3\n        if c == 1\n          fmod = Integer(line)\n        end\n        if c == 2\n          f = []\n        end\n        if c == 4\n          f[0] = Integer(line)\n        end\n        if c == 5\n          f[1] = Integer(line)\n        end\n        if c == 6\n          f[2] = Integer(line)\n          if fmod == 3\n            verts = [v[l[f[0]][0]], v[l[f[0]][1]], v[l[f[1]][0]], v[l[f[1]][1]], v[l[f[2]][0]], v[l[f[2]][1]]]\n            verts.uniq!\n            begin\n              entities.add_face verts\n            rescue\n              UI.messagebox fmod\n            end\n            c = 0\n          end\n        end\n        if c == 7\n          f[3] = Integer(line)\n          if fmod == 4\n            verts = [v[l[f[0]][0]], v[l[f[0]][1]], v[l[f[1]][0]], v[l[f[1]][1]], v[l[f[2]][0]], v[l[f[2]][1]] , v[l[f[3]][0]], v[l[f[3]][1]]]\n            verts.uniq!\n            begin\n              entities.add_face verts\n            rescue\n              entities.add_face [verts[0], verts[1], verts[2]]\n              entities.add_face [verts[2], verts[3], verts[0]]\n            end\n            c = 0\n          end\n        end\n      end\n    end\n  end\nend\n\nif (not file_loaded?(\"rok_ld.rb\"))\n  UI.menu(\"Plugin\").add_item(\"rok_loader\") {rok_ld}\nend\n\nfile_loaded(\"rok_ld.rb\")\n\n```\n\n", "tags": ["SketchUp", "Ruby", "ROK"]}