{"context": "\n\n\u6982\u8981\nSketchUp\u3067OBJ\u30d5\u30a1\u30a4\u30eb\u3092\u8aad\u307f\u8fbc\u3093\u3067\u898b\u305f\u3002\n\n\u5199\u771f\n\n\n\u74b0\u5883\nSketchUp\nv7.1.6860\nv8.0.16846\n\n\u30b5\u30f3\u30d7\u30eb\u30b3\u30fc\u30c9\nobj_ld.rb\nrequire \"sketchup.rb\"\n\ndef obj_ld\n  entities = Sketchup.active_model.entities\n  groups = {}\n  vertices = []\n  f = UI.openpanel \"Select .obj file\", \"\", \"*.obj\"\n  return unless f\n  lines = IO.readlines(f)\n  lines.each do | line |\n    next if line[0] == ?#\n    line.strip!\n    values = line.split\n    next if values.length == 0\n    cmd = values.shift\n    case cmd\n    when \"v\"\n      v = values.map {| e | Float(e)}\n      vertices << v\n    when \"g\"\n      gname = values.join \"_\"\n      if (groups[gname].nil?)\n        groups[gname] =  Sketchup.active_model.entities.add_group\n        groups[gname].name = gname\n      end\n      entities = groups[gname].entities\n    when \"f\"\n      face = []\n      values.each do | v |\n        w = v.split(\"/\")\n        face << Integer(w[0])\n    end\n    verts = face.map {| v | vertices[v - 1]}\n    begin\n      entities.add_face verts\n    rescue\n      #UI.messagebox line\n    end\n    end\n  end \nend\n\nif (not file_loaded?(\"obj_ld.rb\"))\n  UI.menu(\"Plugin\").add_item(\"obj_loader\") {obj_ld}\nend\n\nfile_loaded(\"obj_ld.rb\")\n\n\n#\u6982\u8981\nSketchUp\u3067OBJ\u30d5\u30a1\u30a4\u30eb\u3092\u8aad\u307f\u8fbc\u3093\u3067\u898b\u305f\u3002\n\n#\u5199\u771f\n![obj.jpg](https://qiita-image-store.s3.amazonaws.com/0/18104/d607a07f-908a-666e-2fe0-5e46c76372ff.jpeg)\n\n\n#\u74b0\u5883\nSketchUp\nv7.1.6860\nv8.0.16846\n\n\n#\u30b5\u30f3\u30d7\u30eb\u30b3\u30fc\u30c9\nobj_ld.rb\n\n```\nrequire \"sketchup.rb\"\n\ndef obj_ld\n  entities = Sketchup.active_model.entities\n  groups = {}\n  vertices = []\n  f = UI.openpanel \"Select .obj file\", \"\", \"*.obj\"\n  return unless f\n  lines = IO.readlines(f)\n  lines.each do | line |\n    next if line[0] == ?#\n    line.strip!\n    values = line.split\n    next if values.length == 0\n    cmd = values.shift\n    case cmd\n    when \"v\"\n      v = values.map {| e | Float(e)}\n      vertices << v\n    when \"g\"\n      gname = values.join \"_\"\n      if (groups[gname].nil?)\n        groups[gname] =  Sketchup.active_model.entities.add_group\n        groups[gname].name = gname\n      end\n      entities = groups[gname].entities\n    when \"f\"\n      face = []\n      values.each do | v |\n        w = v.split(\"/\")\n        face << Integer(w[0])\n    end\n    verts = face.map {| v | vertices[v - 1]}\n    begin\n      entities.add_face verts\n    rescue\n      #UI.messagebox line\n    end\n    end\n  end \nend\n\nif (not file_loaded?(\"obj_ld.rb\"))\n  UI.menu(\"Plugin\").add_item(\"obj_loader\") {obj_ld}\nend\n\nfile_loaded(\"obj_ld.rb\")\n\n```\n\n", "tags": ["SketchUp", "Ruby", "obj"]}